# Generated by Django 5.1.2 on 2025-01-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loujinha', '0002_category_alter_products_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
